
package View;

import models.AbstractPerson;
import models.Daycare;
import models.Student;
import models.Instructor;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import javax.swing.table.DefaultTableModel;


public class InstuctorProfile extends javax.swing.JPanel {

    private JPanel container;
    private Daycare daycare;
    private AbstractPerson teacher;


    public InstuctorProfile(JPanel container, AbstractPerson teacher) {
        initComponents();
        this.container = container;
        this.teacher = teacher;
        firstNameTf.setText(teacher.getFirstName());
        lastNameTf.setText(teacher.getLastName());
        ageTf.setText(String.valueOf(teacher.getAge()));
        idTf.setText(String.valueOf(teacher.getId()));

        Instructor t = (Instructor) teacher;
        classroomTf.setText(String.valueOf(t.getClassroomId()));
//        wageTf.setText(String.valueOf(t.getWage()));
        reviewDateTf.setText(t.getDateOfReview().toString());
        NextReviewDateTf.setText(String.valueOf(t.getDaysForReview()) + " days");
        classRoomSizeTf.setText(String.valueOf(t.getSize()));
        StudentCountTf.setText(String.valueOf(t.getCount()));
        LastReviewScoreTf.setText(String.valueOf(t.getLastReviewScore()));
        

//        for (Student s : t.getStudentList()) {
//            studentsTextArea.append("ID: " + s.getId() + " Name: " + s.getFirstName() + " " + s.getLastName() + "\n");
//        }
        studentsOfTeacherTable.setAutoCreateRowSorter(true);
        DefaultTableModel model = (DefaultTableModel) studentsOfTeacherTable.getModel();
        model.setRowCount(0);
        for (Student s : t.getListStudent()) {
                Object[] row = new Object[2];
                row[0] = s.getId();
                row[1] = s.getFirstName() + "  " + s.getLastName();
                model.addRow(row);}
    }

    private PieDataset createDataset(int count, int size) {
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Students", count);
        dataset.setValue("Space left", size - count);
        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstNameTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ageTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastNameTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        classroomTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        reviewDateTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NextReviewDateTf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LastReviewScoreTf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        classRoomSizeTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        StudentCountTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsOfTeacherTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        teacherphoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 6, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Firstname");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, -1));

        firstNameTf.setEditable(false);
        jPanel2.add(firstNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Age");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 57, -1));

        ageTf.setEditable(false);
        jPanel2.add(ageTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 71, -1));

        idTf.setEditable(false);
        jPanel2.add(idTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 140, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Lastname");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 60, 70, -1));

        lastNameTf.setEditable(false);
        jPanel2.add(lastNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 130, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("Classroom ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        classroomTf.setEditable(false);
        jPanel2.add(classroomTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("Last ReviewDate");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        reviewDateTf.setEditable(false);
        jPanel2.add(reviewDateTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("Next Review Date");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        NextReviewDateTf.setEditable(false);
        NextReviewDateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextReviewDateTfActionPerformed(evt);
            }
        });
        jPanel2.add(NextReviewDateTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 130, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setText("Last Review Score");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        LastReviewScoreTf.setEditable(false);
        LastReviewScoreTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastReviewScoreTfActionPerformed(evt);
            }
        });
        jPanel2.add(LastReviewScoreTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 140, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 255));
        jLabel12.setText("Classroom Size");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 110, -1));

        classRoomSizeTf.setEditable(false);
        jPanel2.add(classRoomSizeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 120, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 153, 255));
        jLabel13.setText("Student Count");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        StudentCountTf.setEditable(false);
        jPanel2.add(StudentCountTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 140, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 120, 680, 340));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" Students List");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 192, -1));

        studentsOfTeacherTable.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        studentsOfTeacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "StudentId", "Student Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentsOfTeacherTable);
        studentsOfTeacherTable.getAccessibleContext().setAccessibleName("TeacherStudentTable");

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 297, 150));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teacher's Profile");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 210, -1));

        backButton.setBackground(new java.awt.Color(51, 153, 255));
        backButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, -1));

        teacherphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacher8.png"))); // NOI18N
        teacherphoto.setText("jLabel6");
        teacherphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        add(teacherphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 130, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButtonActionPerformed

    private void NextReviewDateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextReviewDateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextReviewDateTfActionPerformed

    private void LastReviewScoreTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastReviewScoreTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastReviewScoreTfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LastReviewScoreTf;
    private javax.swing.JTextField NextReviewDateTf;
    private javax.swing.JTextField StudentCountTf;
    private javax.swing.JTextField ageTf;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField classRoomSizeTf;
    private javax.swing.JTextField classroomTf;
    private javax.swing.JTextField firstNameTf;
    private javax.swing.JTextField idTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTf;
    private javax.swing.JTextField reviewDateTf;
    private javax.swing.JTable studentsOfTeacherTable;
    private javax.swing.JLabel teacherphoto;
    // End of variables declaration//GEN-END:variables
}
