
package View;

import java.awt.CardLayout;


public class StudentRecords extends javax.swing.JPanel {

    /**
     * Creates new form StudentsPanel
     */
    public StudentRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        addStudentButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        viewStudentButton = new javax.swing.JButton();
        registrationButton = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Database");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 370, 46));

        backButton.setBackground(new java.awt.Color(255, 102, 204));
        backButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        studentsTable.setBackground(new java.awt.Color(233, 230, 230));
        studentsTable.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        studentsTable.setForeground(new java.awt.Color(0, 0, 102));
        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Age", "FirstName", "LastName", "Father Name", "Mother Name", "Address", "Phone Number", "Need Renewal", "Enrolled on", "Renewal on", "Teacher ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studentsTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        studentsTable.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(studentsTable);
        if (studentsTable.getColumnModel().getColumnCount() > 0) {
            studentsTable.getColumnModel().getColumn(0).setMinWidth(1);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 930, 416));

        addStudentButton.setBackground(new java.awt.Color(255, 102, 204));
        addStudentButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        addStudentButton.setText("Add");
        addStudentButton.setFocusPainted(false);
        addStudentButton.setFocusTraversalKeysEnabled(false);
        addStudentButton.setFocusable(false);
        addStudentButton.setRequestFocusEnabled(false);
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 100, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2204, 76, 145, 372));

        viewStudentButton.setBackground(new java.awt.Color(255, 102, 204));
        viewStudentButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        viewStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        viewStudentButton.setText("Update");
        viewStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentButtonActionPerformed(evt);
            }
        });
        jPanel2.add(viewStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, 100, -1));

        registrationButton.setBackground(new java.awt.Color(255, 102, 204));
        registrationButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        registrationButton.setForeground(new java.awt.Color(255, 255, 255));
        registrationButton.setText("Register");
        registrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButtonActionPerformed(evt);
            }
        });
        jPanel2.add(registrationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 100, -1));

        deleteButton1.setBackground(new java.awt.Color(255, 102, 204));
        deleteButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        deleteButton1.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton1.setText("Delete");
        jPanel2.add(deleteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 110, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studban4.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 610, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void registrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void viewStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewStudentButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addStudentButton;
    public javax.swing.JButton backButton;
    public javax.swing.JButton deleteButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton registrationButton;
    public javax.swing.JTable studentsTable;
    public javax.swing.JButton viewStudentButton;
    // End of variables declaration//GEN-END:variables
}
